version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.16.0
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "42:02:6c:d0:4a:45:af:b8:da:a8:b1:0e:dc:25:d1:2c"
      
      - checkout

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Installing dependenices
          command: yarn install --frozen-lockfile

      - run:
          name: Build library
          command: yarn build

      - run:
          name: Zipping dist folder for release
          command: yarn zip

      - run:
          name: Publishing NPM Package
          command: npm run release
